[build-system]
requires = [
  "setuptools >= 42",
  "wheel",
  "setuptools_scm[toml]>=3.4"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "calciumcurator/_version.py"

[tool.black]
target-version = ['py36', 'py37', 'py38']
skip-string-normalization = true
line-length = 79
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | examples
    | vendored
  )/
)
'''

[tool.check-manifest]
ignore = [
  ".pre-commit-config.yaml",
  "Makefile",
  "calciumcurator/_version.py",  # added during build by setuptools_scm
]